name: GithubActionsRelease

on:
  push:
    tags:
      - '*' # Push events to matching *, i.e. 1.0, 20.15.10



env:
  blazorServerAppName: 'website-2203-blazor-server'
  blazorWebAssemblyAppName: 'website-2203-blazor-webassembly'
  project: 'Website.Server/Website.Server.csproj'
  registryName: 'dioptraregistry'



jobs:

############################################################################################################
# These jobs are used to gate actions. By creating these jobs we don't need to proliferate the repo checks
############################################################################################################
  is-on-dioptra:
    name: Running on Dioptra/Website.2203?
    runs-on: ubuntu-latest
    if: github.repository == 'Dioptra/Website.2203'
    steps:
    - name: Nothing to see here
      run: echo ""



############################################################################################################
# Set unified suffix
############################################################################################################
  set-suffix:
    name: Create the date based suffix
    needs: [perform-deployment]
    runs-on: ubuntu-latest
    outputs:
      outputSuffix: ${{ steps.setSuffix.outputs.GlobalSuffix }}

    steps:
    - id: setSuffix
      run: echo "GlobalSuffix=$(date +'%Y-%m-%d--%H-%M-%S')--${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      shell: bash

############################################################################################################
# Build blazor server container on Dioptra
############################################################################################################
  build-blazor-server:
    name: Build BlazorServer
    needs: [is-on-dioptra, set-suffix]
    runs-on: ubuntu-latest

    steps:
    - name: Retrieve the global suffix
      run: echo "suffix=${{needs.set-suffix.outputs.outputSuffix}}" >> $GITHUB_ENV
      shell: bash

    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it üõéÔ∏è
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
        dotnet-quality: 'preview'

    - name: 'Build and push docker container'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: dotnet publish ${{env.project}} --os linux --arch x64 --configuration Release_Server -p:PublishProfile=DefaultContainer -p:Version=${{ env.suffix }} -p:ContainerRegistry=${{env.registryname}} -p:ContainerRepository=${{env.blazorServerAppName}} -p:ContainerImageTag=${{ env.suffix }} --self-contained
        

############################################################################################################
# Build blazor webassembly container on Dioptra
############################################################################################################
  build-blazor-webassembly:
    name: Build BlazorWASM
    needs: [set-suffix, is-on-dioptra]
    runs-on: ubuntu-latest

    steps:
    - name: Retrieve the global suffix
      run: echo "suffix=${{needs.set-suffix.outputs.outputSuffix}}" >> $GITHUB_ENV
      shell: bash

    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it üõéÔ∏è
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'
        dotnet-quality: 'preview'

    - name: 'Build and push docker container'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: dotnet publish ${{env.project}} --os linux --arch x64 --configuration Release_Server -p:PublishProfile=DefaultContainer -p:Version=${{ env.suffix }} -p:ContainerRegistry=${{env.registryname}} -p:ContainerRepository=${{env.blazorWebAssemblyAppName}} -p:ContainerImageTag=${{ env.suffix }} --self-contained



############################################################################################################
# Create release
############################################################################################################
  create-release:
    name: Create release
    needs: [set-suffix, build-blazor-server, build-blazor-webassembly, is-on-dioptra]

    runs-on: ubuntu-latest

    steps:
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        name: Release ${{ needs.set-suffix.outputs.outputSuffix }}
        tag: ${{ needs.set-suffix.outputs.outputSuffix }}

