name: GithubActionsWIP

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]



env:
  blazorServerDockerFile: './Website.BlazorServer/Dockerfile'
  blazorWebAssemblyDockerFile: './Website.BlazorWebAssembly/Server/Dockerfile'



jobs:

############################################################################################################
# Store the version information
############################################################################################################
  version:
    name: Set version suffix
    runs-on: ubuntu-latest

    steps:
    - id: get
      run: |
        echo "::set-output name=suffix::$(date +'%Y-%m-%d--%H-%M-%S')--0.0.0"
    - id: show
      run: |
        echo "Suffix:     ${{ steps.get.outputs.suffix }}"
    outputs:
      suffix: ${{ steps.get.outputs.suffix }}
      
      

############################################################################################################
# Build blazor server container
############################################################################################################
  build-blazor-server:
    name: Build Website.BlazorServer docker container
    needs: [version]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: 'Build docker container'
      run: |
        docker build . --file ${{ env.blazorServerDockerFile }} --build-arg version=${{ needs.version.outputs.suffix }}
      


############################################################################################################
# Build blazor webassembly container
############################################################################################################
  build-blazor-webassembly:
    name: Build Website.BlazorWebAssembly docker container
    needs: [version]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: 'Build docker container'
      run: |
        docker build . --file ${{ env.blazorWebAssemblyDockerFile }} --build-arg version=${{ needs.version.outputs.suffix }}
        