name: GithubActionsWIP

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - 'main'



env:
  blazorServerDockerFile: './Website.BlazorServer/Dockerfile'
  blazorWebAssemblyDockerFile: './Website.BlazorWebAssembly/Server/Dockerfile'



jobs:

############################################################################################################
# Build blazor server container
############################################################################################################
  build-blazor-server:
    name: Build BlazorServer docker container
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: 'Build docker container'
      run: |
        docker build . --file ${{ env.blazorServerDockerFile }}
      


############################################################################################################
# Build blazor webassembly container
############################################################################################################
  build-blazor-webassembly:
    name: Build BlazorWebAssembly docker container
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: 'Build docker container'
      run: |
        docker build . --file ${{ env.blazorWebAssemblyDockerFile }}
        