name: GithubActionsWIP

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]



env:
  blazorServerDockerFile: './Website.BlazorServer/Dockerfile'
  blazorWebAssemblyDockerFile: './Website.BlazorWebAssembly/Server/Dockerfile'



jobs:

############################################################################################################
# Store the version information
############################################################################################################
  version:
    name: Set version suffix
    runs-on: ubuntu-latest

    steps:
    - id: get
      run: |
        echo "::set-output name=buildTime::$(date +'%Y-%m-%d--%H-%M-%S')"
        echo "::set-output name=version::${GITHUB_REF/refs\/tags\//}"
        echo "::set-output name=suffix::$(date +'%Y-%m-%d--%H-%M-%S')--${GITHUB_REF/refs\/tags\//}"
    - id: show
      run: |
        echo "Build Time: ${{ steps.get.outputs.buildTime }}"
        echo "Version:    ${{ steps.get.outputs.version }}"
        echo "Suffix:     ${{ steps.get.outputs.suffix }}"
    outputs:
      buildTime: ${{ steps.get.outputs.buildTime }}
      version: ${{ steps.get.outputs.version }}
      suffix: ${{ steps.get.outputs.suffix }}
      
      

############################################################################################################
# Build blazor server container
# This is hard-skipped when we only want to perform a comparison (github.event_name != 'workflow_dispatch')
############################################################################################################
  build-blazor-server:
    name: Build Website.BlazorServer docker container
    needs: [version]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: 'Build docker container'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . --file ${{ env.blazorServerDockerFile }} --build-arg build-time=${{ needs.version.outputs.buildTime }} --build-arg version="1.2.3"
      


############################################################################################################
# Build blazor webassembly container
# This is hard-skipped when we only want to perform a comparison (github.event_name != 'workflow_dispatch')
############################################################################################################
  build-blazor-webassembly:
    name: Build Website.BlazorWebAssembly docker container
    needs: [version]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository under $GITHUB_WORKSPACE so the job can access it 🛎️
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: 'Build docker container'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . --file ${{ env.blazorWebAssemblyDockerFile }} --build-arg build-time=${{ needs.version.outputs.buildTime }} --build-arg version="1.2.3"
        